<?php
/**
 * Created by PhpStorm.
 * User: momo
 * Date: 2017/11/8
 * Time: 下午1:56
 */
header("Content-type: text/html; charset=utf-8");
ini_set("display_errors", "On");
error_reporting(E_ALL | E_STRICT);
date_default_timezone_set('Asia/Shanghai');
require 'vendor/autoload.php';

$git = new PHPGit\Git();

$git->setRepository('/data/wiki.opqnext.com/wiki');

$hash = strval($_GET['hash']);
//
//echo $hash;
//var_dump($git->tree('master'));

$a = ['oneline', 'short', 'medium', 'full', 'fuller', 'email'];

$res =  $git->show($hash,['format'=>'oneline','abbrev-commit'=>true]);


echo str_replace("\n","\n",$res);
?>
<html>
    <head>
        <!-- Stylesheet -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/styles/github.min.css">
        <link rel="stylesheet" type="text/css" href="dist/diff2html.css">

        <!-- Javascripts -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.3/jquery.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/languages/scala.min.js"></script>
        <!-- Javascripts -->
        <script type="text/javascript" src="dist/diff2html.js"></script>
        <script type="text/javascript" src="dist/diff2html-ui.js"></script>
    </head>

    <body>
        <div id="html-target-elem">

        </div>

        <div class="html-target-elem">

        </div>

        <script>
            $(document).ready(function() {
                ///let diff2html = require("diff2html").Diff2Html;
                //var strInput = "--- a/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n+++ b/server/vendor/golang.org/x/sys/unix/zsyscall_linux_mipsle.go\n@@ -1035,6 +1035,17 @@ func Prctl(option int, arg2 uintptr, arg3 uintptr, arg4 uintptr, arg5 uintptr) (\n \n // THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n \n+func Pselect(nfd int, r *FdSet, w *FdSet, e *FdSet, timeout *Timespec, sigmask *Sigset_t) (n int, err error) {\n+\tr0, _, e1 := Syscall6(SYS_PSELECT6, uintptr(nfd), uintptr(unsafe.Pointer(r)), uintptr(unsafe.Pointer(w)), uintptr(unsafe.Pointer(e)), uintptr(unsafe.Pointer(timeout)), uintptr(unsafe.Pointer(sigmask)))\n+\tn = int(r0)\n+\tif e1 != 0 {\n+\t\terr = errnoErr(e1)\n+\t}\n+\treturn\n+}\n+\n+// THIS FILE IS GENERATED BY THE COMMAND AT THE TOP; DO NOT EDIT\n+\n func read(fd int, p []byte) (n int, err error) {\n \tvar _p0 unsafe.Pointer\n \tif len(p) > 0 {\n";
                //var diff2htmlUi = new Diff2HtmlUI({diff: "f9eb2d4 修改了MTZ文件\ndiff --git a/8.html b/8.html\nindex 4d9495e..6bce554 100644\n--- a/8.html\n+++ b/8.html\n @@ -3,8 +3,9 @@\n听少爷说他在说这些不是我的错\n难道说这么多都是孩儿惹的祸\n阿玛说阿玛说人生不可重来过\n-废话还是最好尽量地少说为妙\n+1. 年轻的确很美但骄傲是你不对\n- 应该关爱社会你也得感动落泪\n- 不管你是否想要简化些的思维\n-- 年轻的确很美但骄傲是你不对\n\ No newline at end of file\n+1. 年轻的确很美但骄傲是你不对\n+2. 年轻的确很美但骄傲是你不对\n"});
                var diff2htmlUi = new Diff2HtmlUI({diff: "<?php echo str_replace("\n","\n",$res);?>"});
                //var diff2htmlUi = new Diff2HtmlUI({diff: strInput});
                diff2htmlUi.draw('#html-target-elem', {inputFormat: 'diff', showFiles: true, matching: 'lines'});
                diff2htmlUi.fileListCloseable('#line-by-line', false);
            });
        </script>
    </body>
</html>